### ISSUE TITLE
question: can it work with Sonarr, Radarr etc

### ISSUE THREAD

**Issue by zilexa** [lu6fer/rtorrent-flood#1]
Is the socket available for other docker applications to use?

**Comment by fhunkeler** [comment]
Hi, 
you can use 


Parameter | Function
-- | --
-e RTORRENT_SOCK=true | using socket file or scgi port for rtorrent communication
-e RTORRENT_SOCK_PATH=/config/.sessions/rtorrent.sock | where the socket is located if RTORRENT_SOCK=true

To create a socket and make it available to container by mapping socket to it, or 

Parameter | Function
-- | --
-e WEBSERVER_PORT=80 | scgi port to use
-e RPC_USER="admin" | User name for rtorrent XML-RPC connection
-e RPC_PASSWORD="rtorrentadmin" | Password for rtorrent XML-RPC connection
 
To create HTTP based port listenting with creadentials. And configure services such as sonarr/radarr... (see screenshot - sonarr rtorrent configuration)
Host must be the flood container name in non default docker network, or IP in default docker network

![Capture d’écran du 2020-03-30 09-57-12](https://user-images.githubusercontent.com/22212522/77888740-fe7f2000-726c-11ea-839d-a773a85f313f.png)

**Comment by zilexa** [comment]
Wow thanks so much for your quick and complete response. I guess you use this as well :)
I like the FloodUI and the fact rTorrent is lightweight. Currently still using Transmission but I do not like the limitations of the UI regarding settings and the fact that all downloads fail when I restart Transmission docker. 
But rTorrent+Flood seemed quite complex, requiring nginx and who knows what more. Not sure if it is still lightweight compared to Transmission. But you are making the switch very easy now :)
